[phases.setup]
nixPkgs = [
    "php82",
    "php82Extensions.bcmath",
    "php82Extensions.pdo_pgsql",
    "php82Extensions.pgsql",
    "php82Extensions.mbstring",
    "php82Extensions.xml",
    "php82Extensions.curl",
    "php82Extensions.zip",
    "php82Extensions.gd",
    "nodejs-22_x"
]

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "php artisan config:clear",
    "php artisan route:clear",
    "php artisan view:clear",
    "npm ci",
    "chmod +x deploy.sh"
]